name: Deploy Frontend

on:
  push:
    branches:
      - haegi

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Vite App with VITE_BASE_URL
        run: |
          echo "VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}" >> .env
          npm run build

      - name: Create deploy directory on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 8807
          script: |
            mkdir -p /home/haegi/mbn-front/dist

      - name: Upload build via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 8807
          source: 'dist/**'
          target: '/home/haegi/mbn-front/dist'

      - name: Restart app with PM2 and SPA routing
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 8807
          script: |
            cd /home/haegi/mbn-front
            pm2 delete mbn-front || true
            pm2 serve dist 3333 --spa --name "mbn-front"
            pm2 save
