name: Deploy Frontend

on:
  push:
    branches:
      - haegi # 사용 중인 브랜치명

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Vite App
        run: npm run build

      - name: Copy build files to server via SSH
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 8807
          source: 'dist/*'
          target: '/home/haegi/mbn-front'

      - name: Start app with PM2 on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 8807
          script: |
            cd /home/haegi/mbn-front
            pm2 delete mbn-front || true
            pm2 start npm --name "mbn-front" -- run preview -- --port 3333 --host
            pm2 save
