name: Deploy Frontend

on:
  push:
    branches:
      - haegi # 또는 너가 사용하는 브랜치

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Deploy to Server via SSH
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: 'dist/*' # 또는 "build/*" → Vite냐 CRA냐에 따라
          target: '/home/haegi/mbn-front' # 너의 서버 경로에 맞게 수정

# 예: 코멘트 하나 추가
# This workflow deploys frontend via SSH
